### ISSUE TITLE
Missing Vagrant

### ISSUE THREAD

**Issue by liemle3893** [hashicorp/homebrew-tap#68] opened 2020-10-17 06:00 UTC
I'm have just `brew uninstall vagrant` and then I realized that there's no `hashicorp/tap/vagrant`. Will you add it soon?

**Comment by socheatsok78** [comment] 2020-10-18 04:20
I'm surprised that `vagrant` is not there 😅!

**Comment by kpenfound** [comment] 2020-10-19 16:42
Hello! We should definitely update our README to reflect this, but -
Vagrant is currently available as a cask in core which pulls from our official releases site.  It's packaged as a cask rather than a formula to include several dependencies which vagrant requires.

Currently we recommend `brew cask install vagrant`.

I know the concept of cask and formula are currently being merged/mixed in brew, so I'll look into what that means for our tap and cask distribution!

**Closed by kpenfound** 2020-10-19 16:42 UTC

**Comment by mdaniel** [comment] 2021-05-19 18:24
I don't know how to link directly to it, but [the Vagrant downloads page](https://www.vagrantup.com/downloads) has a Homebrew sub-tab which specifically says "run `brew tap hashicorp/tap` then run `brew install hashicorp/tap/vagrant`" and if one follows those instructions it results in an error

**Comment by kpenfound** [comment] 2021-05-19 18:29
Thanks for reporting that @mdaniel ! It is indeed incorrect, I'll make sure it gets updated

**Comment by mdaniel** [comment] 2021-05-19 18:31
I don't know against which project to report a related bug, but if one follows the Ubuntu instructions on that same page, it still shows the latest version as 2.2.15

**Comment by paulettea** [comment] 2021-05-19 18:36
Try: brew install vagrant

**Comment by kpenfound** [comment] 2021-05-19 18:42
@mdaniel like apt shows the latest as 2.2.15 after adding the repo? Which version of ubuntu is that on so I can check the metadata?

**Comment by mdaniel** [comment] 2021-05-19 21:00
Yes, after following the `apt-add-repository` I ended up with `deb [arch=amd64] https://apt.releases.hashicorp.com groovy main` but while digging up the supporting evidence for this, I noticed that the standalone `.deb` (which used to be the way that downloads page supported Ubuntu) has a `1:` epoch(?)  but the apt repos apparently do not. So perhaps the instructions may need to say "if you have ever installed via the directly downloaded deb, you will want to `apt remove vagrant` first:

```console
$ apt-cache show vagrant
Package: vagrant
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 112466
Maintainer: HashiCorp <support@hashicorp.com>
Architecture: amd64
Version: 1:2.2.16
Description: no description given
Description-md5: c0af8b65ef8df63b3bfb124d96da1778
License: unknown
Vendor: root@vagrant
Homepage: https://www.vagrantup.com/

Package: vagrant
Version: 2.2.16
License: MIT
Vendor: HashiCorp
Architecture: amd64
Maintainer: HashiCorp <support@hashicorp.com>
Installed-Size: 112466
Section: default
Priority: extra
Homepage: https://www.vagrantup.com/
Description: Vagrant is a tool for building and distributing development environments.
Description-md5: 2bef0c3fc60e83db8996e2e5a37d9365
Filename: pool/amd64/main/vagrant_2.2.16_amd64.deb
SHA1: b6bfe392fc1d83e5ad56db993163cce21e865ee4
SHA256: dca00147e0e016257411a8684e6e0d4394fe5f9aa7de1c94a6f9534107b1e658
Size: 40882122
```
:point_up: is after I gave up and downloaded the "old" style `vagrant_2.2.16_x86_64.deb` but I'd bet it's the same root cause from when I had `1:2.2.15` installed

**Comment by kpenfound** [comment] 2021-05-19 21:04
@mdaniel Ah yes, I'm glad you figured that out! I'll see if we can get that documented

**Comment by jeffsw** [comment] 2021-06-08 17:02
The macOS tab on the downloads page https://www.vagrantup.com/downloads still incorrectly instructs users to use a tap.

**Comment by kpenfound** [comment] 2021-08-20 15:39
Sorry for the delay here folks, fixed in https://github.com/hashicorp/vagrant/pull/12499
